# Generated by Django 2.0.5 on 2018-08-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loansApp', '0002_loan_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Préstamos'},
        ),
    ]
