# Generated by Django 2.0.5 on 2018-08-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Reservas'},
        ),
    ]
