# Generated by Django 2.0.5 on 2018-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacesApp', '0002_auto_20180817_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
