# Generated by Django 2.0.5 on 2018-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/items', verbose_name='Imagen del articulo'),
        ),
    ]
